package com.staynest.api.enums;

public enum NotificationType {
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_REQUEST_RECEIVED,
    LISTING_APPROVED,
    LISTING_REJECTED,
    LISTING_CHANGES_REQUESTED,
    LISTING_SUSPENDED,
    REVIEW_RECEIVED,
    MESSAGE_RECEIVED,
    HOST_APPLICATION_APPROVED,
    HOST_APPLICATION_REJECTED,
    PASSWORD_RESET,
    EMAIL_VERIFIED
}
